ctrl_interface=/var/run/wpa_supplicant
update_config=1
device_name=ExCast-123456
config_methods=virtual_display virtual_push_button
persistent_reconnect=1
device_type=1-0050F204-1
p2p_no_group_iface=1
pmf=1

network={
	ssid="DIRECT-DW-T2"
	bssid=5e:dd:a6:e5:d2:30
	psk=54c14f2ab1715f7dff9b1e711d7f2a6e7a680ebcd48731ed98069567556b6140
	proto=RSN
	key_mgmt=WPA-PSK
	pairwise=CCMP
	auth_alg=OPEN
	disabled=2
}
