# # 网卡接口
# interface wlan1
# # IP 地址池范围
# start 192.168.49.100
# end 192.168.49.200
# # 子网掩码
# option subnet 255.255.255.0
# # 网关
# option router 192.168.49.1
# # DNS 服务器
# option dns 8.8.8.8
# # 租期（秒）
# option lease 86400
# # PID 文件路径
# pidfile /var/run/udhcpd.pid


# 网卡接口
interface wlan1
# 子网声明
subnet 192.168.49.0 255.255.255.0
# IP 地址池范围
start 192.168.49.100
end 192.168.49.200
# 网关
option router 192.168.49.1
# DNS 服务器
option dns 8.8.8.8
# 子网掩码
option subnet 255.255.255.0
# 租期（秒）
lease 86400
# 允许保留旧租约
remaining yes
# PID 文件路径
pidfile /var/run/udhcpd.pid

max_leases 101
