TEST_KEY_SUSPEND_VERSION =
TEST_KEY_SUSPEND_ENABLE_TARBALL = NO
TEST_KEY_SUSPEND_ENABLE_PATCH = NO

TEST_KEY_SUSPEND_DEPENDENCIES += test-common

TEST_KEY_SUSPEND_CONF_OPTS += -DCMAKE_INSTALL_PREFIX=/usr/local
$(eval $(cmake-package))
