# SPDX-License-Identifier: GPL-2.0
#
# Makefile for ArtInChip SoC clk
#

obj-$(CONFIG_$(SPL_TPL_)CLK_ARTINCHIP_CMU_DRIVER_V1) += clk-artinchip.o
obj-$(CONFIG_$(SPL_TPL_)CLK_ARTINCHIP_CMU_DRIVER_V2) += clk-artinchip-v2.o
obj-$(CONFIG_$(SPL_TPL_)CLK_ARTINCHIP_CMU_V1_0) += aic-cmu.o
obj-$(CONFIG_CLK_ARTINCHIP)	+= clk-cmd.o