WIFI_P2P_CONFIG_VERSION =
WIFI_P2P_CONFIG_ENABLE_TARBALL = NO
WIFI_P2P_CONFIG_ENABLE_PATCH = NO

WIFI_P2P_CONFIG_DEPENDENCIES += wpa_supplicant

WIFI_CONFIG_CONF_OPTS += -DCMAKE_INSTALL_PREFIX=/usr/local
$(eval $(cmake-package))
