ctrl_interface=/var/run/wpa_supplicant
update_config=1
device_name=p2p_test
device_type=10-0050F204-5
#config_methods=display push_button keypad virtual_push_button physical_display
p2p_ssid_postfix=-MY_P2P_AP
p2p_go_intent=15
p2p_oper_channel=1
p2p_listen_channel=1

#p2p_add_cli_chan=1
#pmf=1
#p2p_go_he=1
#p2p_group_idle=10
#p2p_no_group_iface=1

network={
    ssid="MY_P2P_AP"
    psk="12345678"
    proto=RSN
    pairwise=CCMP
    mode=3
    disabled=0
}
