AIC_CAST_VERSION =
AIC_CAST_ENABLE_TARBALL = NO
AIC_CAST_ENABLE_PATCH = NO
AIC_CAST_INSTALL_STAGING = YES

AIC_CAST_DEPENDENCIES += openssl libnl libpcap libev aic-mpp
AIC_CAST_CONF_OPTS += -DCMAKE_INSTALL_PREFIX=/usr

ifeq ($(BR2_PACKAGE_AIC_CASE_ENABLE_AUDIO),y)
AIC_CAST_DEPENDENCIES += alsa-lib fdk-aac
AIC_CAST_CONF_OPTS += -DENABLE_AUDIO=enable
AIC_MPP_DEPENDENCIES += alsa-lib faad2
AIC_MPP_CONF_OPTS += -DMIDDLEWARE=enable -DAAC_DECODER=enable -DENABLE_AUDIO=enable
endif

AIC_CAST_CONF_OPTS += -DGNU_TARGET_NAME=$(GNU_TARGET_NAME)

AIC_CAST_CONF_OPTS += -DCMAKE_INSTALL_PREFIX=/usr/local

define AIC_CAST_REMOVE_HEADERS_IN_TARGET
	rm -rf $(TARGET_DIR)/usr/local/include/
endef
AIC_CAST_POST_INSTALL_TARGET_HOOKS += AIC_CAST_REMOVE_HEADERS_IN_TARGET

$(eval $(cmake-package))

