TEST_SDMC_VERSION =
TEST_SDMC_ENABLE_TARBALL = NO
TEST_SDMC_ENABLE_PATCH = NO

TEST_SDMC_DEPENDENCIES += test-common

TEST_SDMC_CONF_OPTS += -DCMAKE_INSTALL_PREFIX=/usr/local
$(eval $(cmake-package))
