WIFI_AP_CONFIG_VERSION =
WIFI_AP_CONFIG_ENABLE_TARBALL = NO
WIFI_AP_CONFIG_ENABLE_PATCH = NO

WIFI_AP_CONFIG_DEPENDENCIES += hostapd
WIFI_AP_CONFIG_DEPENDENCIES += wpa_supplicant

WIFI_AP_CONFIG_CONF_OPTS += -DCMAKE_INSTALL_PREFIX=/usr/local
$(eval $(cmake-package))
