AIC_MPP_VERSION =
AIC_MPP_ENABLE_TARBALL = NO
AIC_MPP_ENABLE_PATCH = NO
AIC_MPP_INSTALL_STAGING = YES

AIC_MPP_DEPENDENCIES += test-common
ifeq ("$(BR2_riscv)","y")
AIC_MPP_CONF_OPTS += -DCMAKE_INSTALL_PREFIX=/usr/local -DARCH=RISCV
endif
ifeq ("$(BR2_arm)","y")
AIC_MPP_CONF_OPTS += -DCMAKE_INSTALL_PREFIX=/usr/local -DARCH=ARM
endif

ifeq ($(BR2_PACKAGE_AIC_MPP_RENDER_DRM),y)
AIC_MPP_DEPENDENCIES += libdrm
AIC_MPP_CONF_OPTS += -DRENDER_DRM_BACKEND=enable
endif

ifeq ($(BR2_PACKAGE_AIC_MPP_MIDDLEWARE),y)
AIC_MPP_DEPENDENCIES += libmad alsa-lib lwrb
AIC_MPP_CONF_OPTS += -DMIDDLEWARE=enable
AIC_MPP_CONF_OPTS += -DLWRB=enable
endif

ifeq ($(BR2_PACKAGE_AIC_MPP_RECORDER),y)
AIC_MPP_DEPENDENCIES += sqlite
AIC_MPP_CONF_OPTS += -DRECORDER=enable
AIC_MPP_CONF_OPTS += -DSQLITE=enable
endif

ifeq ($(BR2_PACKAGE_AIC_MPP_AAC_DECODER),y)
AIC_MPP_DEPENDENCIES += faad2
AIC_MPP_CONF_OPTS += -DAAC_DECODER=enable
endif

ifeq ($(BR2_PACKAGE_AIC_MPP_APE_DECODER),y)
AIC_MPP_DEPENDENCIES += ape -lm
AIC_MPP_CONF_OPTS += -DAPE_DECODER=enable
endif

ifeq ($(BR2_PACKAGE_AIC_MPP_FLAC_DECODER),y)
AIC_MPP_DEPENDENCIES += flac
AIC_MPP_CONF_OPTS += -DFLAC_DECODER=enable
endif

ifeq ($(BR2_PACKAGE_AIC_MPP_VORBIS_DECODER),y)
AIC_MPP_DEPENDENCIES += libvorbis libogg
AIC_MPP_CONF_OPTS += -DVORBIS_DECODER=enable
endif

ifeq ($(BR2_PACKAGE_AIC_MPP_OPUS_DECODER),y)
AIC_MPP_DEPENDENCIES += opus
AIC_MPP_CONF_OPTS += -DOPUS_DECODER=enable
endif

ifeq ($(BR2_PACKAGE_AIC_MPP_AAC_ELD_DECODER),y)
AIC_MPP_DEPENDENCIES += fdk-aac
AIC_MPP_CONF_OPTS += -DAAC_ELD_DECODER=enable
endif

ifeq ($(BR2_PACKAGE_AIC_MPP_ALAC_DECODER),y)
AIC_MPP_DEPENDENCIES += alac
AIC_MPP_CONF_OPTS += -DALAC_DECODER=enable
endif

ifeq ($(BR2_PACKAGE_AIC_MPP_H264_ENCODER),y)
AIC_MPP_CONF_OPTS += -DH264_ENCODER=enable
endif

ifeq ($(BR2_PACKAGE_AIC_MPP_MPEG12_DECODER),y)
AIC_MPP_CONF_OPTS += -DMPEG12_DECODER=enable
endif

ifeq ($(BR2_PACKAGE_AIC_MPP_MPEG4_DECODER),y)
AIC_MPP_CONF_OPTS += -DMPEG4_DECODER=enable
endif

ifeq ($(BR2_PACKAGE_AIC_MPP_MP3_ENCODER),y)
AIC_MPP_DEPENDENCIES += lame
AIC_MPP_CONF_OPTS += -DMP3_ENCODER=enable
endif

ifeq ($(BR2_PACKAGE_AIC_MPP_AAC_ENCODER),y)
AIC_MPP_DEPENDENCIES += fdk-aac
AIC_MPP_CONF_OPTS += -DAAC_ENCODER=enable
endif

ifeq ($(BR2_PACKAGE_AIC_MPP_WAV_DEMUXER),y)
AIC_MPP_CONF_OPTS += -DWAV_DEMUXER=enable
endif

ifeq ($(BR2_PACKAGE_AIC_MPP_AVI_DEMUXER),y)
AIC_MPP_CONF_OPTS += -DAVI_DEMUXER=enable
endif

ifeq ($(BR2_PACKAGE_AIC_MPP_MKV_DEMUXER),y)
AIC_MPP_CONF_OPTS += -DMKV_DEMUXER=enable
endif

ifeq ($(BR2_PACKAGE_AIC_MPP_TS_DEMUXER),y)
AIC_MPP_CONF_OPTS += -DTS_DEMUXER=enable
endif

ifeq ($(BR2_PACKAGE_AIC_MPP_MPG_DEMUXER),y)
AIC_MPP_CONF_OPTS += -DMPG_DEMUXER=enable
endif

ifeq ($(BR2_PACKAGE_AIC_MPP_PMP_DEMUXER),y)
AIC_MPP_CONF_OPTS += -DPMP_DEMUXER=enable
endif

ifeq ($(BR2_PACKAGE_AIC_MPP_FLV_DEMUXER),y)
AIC_MPP_CONF_OPTS += -DFLV_DEMUXER=enable
endif

ifeq ($(BR2_PACKAGE_AIC_MPP_RTSP_DEMUXER),y)
AIC_MPP_DEPENDENCIES += live555
AIC_MPP_CONF_OPTS += -DRTSP_DEMUXER=enable
AIC_MPP_CONF_OPTS += -DRTSP_INCLUDE=$(STAGING_DIR)/usr/local/include/
endif

ifeq ($(BR2_PACKAGE_AIC_MPP_HLS_DEMUXER),y)
AIC_MPP_CONF_OPTS += -DHLS_DEMUXER=enable
endif

ifeq ($(BR2_PACKAGE_AIC_MPP_OGG_DEMUXER),y)
AIC_MPP_DEPENDENCIES += libogg
AIC_MPP_CONF_OPTS += -DOGG_DEMUXER=enable
endif

ifeq ($(BR2_PACKAGE_AIC_MPP_MP4_MUXER),y)
AIC_MPP_CONF_OPTS += -DMP4_MUXER=enable
endif

ifeq ($(BR2_PACKAGE_AIC_MPP_TS_MUXER),y)
AIC_MPP_CONF_OPTS += -DTS_MUXER=enable
endif

ifeq ($(BR2_PACKAGE_AIC_MPP_HTTP_STREAM),y)
AIC_MPP_DEPENDENCIES += libcurl
AIC_MPP_CONF_OPTS += -DHTTP_STREAM=enable
endif

ifeq ($(BR2_PACKAGE_AIC_MPP_RTP_STREAM),y)
AIC_MPP_CONF_OPTS += -DRTP_STREAM=enable
endif
ifeq ($(BR2_PACKAGE_AIC_MPP_RTP_ENABLE_SORTER),y)
AIC_MPP_CONF_OPTS += -DRTP_SORTER_ENABLE=enable
endif

ifeq ($(BR2_PACKAGE_AIC_MPP_TEST),y)
AIC_MPP_CONF_OPTS += -DMPP_TEST=enable
endif

ifneq ($(BR2_LINUX_KERNEL_CUSTOM_VERSION_VALUE), "5.10")
AIC_MPP_CONF_OPTS += -DLINUX_VERSION_6=enable
endif

define AIC_MPP_REMOVE_HEADERS_IN_TARGET
	rm -rf $(TARGET_DIR)/usr/local/include/
endef
AIC_MPP_POST_INSTALL_TARGET_HOOKS += AIC_MPP_REMOVE_HEADERS_IN_TARGET

$(eval $(cmake-package))
